apiVersion: v1
kind: Secret
metadata:
  name: auth-config-secret
type: Opaque
stringData:
    DB_HOST: {{.Release.Name}}-mysql
    DB_PORT: "3306"
    DB_USER: "gaber"
    DB_PASSWORD: "gaber123"
    DB_NAME: "weatherapp_db"
    SECRET_KEY: "secret123" # for encrypt jwt token
    AUTH_PORT: "8080" # this is the port that app run on auth service itself