apiVersion : v1
kind: ConfigMap
metadata:
    
    name: nginx-cm
    labels:
    {{ include "front-chart.labels" . | nindent 4 }}
data:
    default.conf: |

        #  upstream flask_api { # we define an upstream block to group one or more backend servers (fastapi app) that nginx will proxy requests to and also to make it easier to manage and load balance between multiple backend servers if needed
        #         #here will replace fastapi that is name of service in compose the dns will resolve it to the correct ip address of the container running fastapi to its internal port 5000
        #         server backend:5000;  # internal Docker service name + port
        #         server backend2:5000; # this another diff container on same port no problem 
        #         # server backend3:5000;
        #         # server fastapi:5001;  # if you have multiple instances of FastAPI nginx will load balancing
        #     }
        
        # server{
        #     listen 80; # redirect who go to http to https
        #     server_name localhost;
        #     return 301 https://$host$request_uri;
        # }
        
        # the connection was between nginx contianer and user so directly 
        # need to encrypt the connection 
        # but now this will nginx container just serve static file 
        # alb will face user and will encrypt the connection betwee alb , user throw ACM 
        # then alb will forward the encrypted connection to ingress and ingress will forward it to nginx container
        # so not need to encrypt the connection between ingress and nginx container is internal connection
        # just normal http connection serve static file
        server {
            listen 80;
            # listen 443 ssl;
            server_name localhost;
            # server_name _; # can be like this
        
            # ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
            # ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
            
            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
                }
            
        
        # no reverse proxy needed to backend -svc cause ingress will do this 
        
            # location /api {
            #                         # backend name of the service in docker compose will resolve to ip of the contianer : 5000 internal port inside container 
            #     proxy_pass http://flask_api;
            #     proxy_http_version 1.1;
            #     proxy_set_header Upgrade $http_upgrade;
            #     proxy_set_header Connection 'upgrade';
            #     proxy_set_header Host $host; # here he keeps the host that clinet sent to nginx and forward it to backend like (proxy_server_name) he sends that host name to the backend server and backend can use that host name to generate correct urls in response #here that name is localhost but in production it will be your domain name and backend can use that domain name to generate correct urls in response
            #     proxy_cache_bypass $http_upgrade;
        
            #     proxy_set_header X-Real-IP $remote_addr;
            #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            #     proxy_set_header X-Forwarded-Proto $scheme;
            # }
        }
        