apiVersion: v2 # version of chart 
name: name-of-chart # name of chart
description: test my helm chart 
# you can put logo here for your application

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "1.0.1" # relate change in configuration of chart itself not application 
#-> update this when you change the values.yml change replica from 2 to 5 here change this 
# so the chart changed but the app not changed still have same image same behavior you change only in chart in replica count of chart 
# must be semantic version

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "latest" # relate changes of application itself -> update this when you change the app template files itself  , change image you build deployment on it
# recommended to be semantic version , but not required